// Code generated by protoc-gen-stdrpc. DO NOT EDIT.
//
// plugin: https://github.com/chai2010/protorpc/tree/master/protoc-gen-plugin
// plugin: https://github.com/chai2010/protorpc/tree/master/protoc-gen-stdrpc
//
// source: service.proto

package reverse_service_pb

import (
	"fmt"
	"io"
	"log"
	"net"
	"net/rpc"
	"time"

	"github.com/golang/protobuf/proto"
)

var (
	_ = fmt.Sprint
	_ = io.Reader(nil)
	_ = log.Print
	_ = net.Addr(nil)
	_ = rpc.Call{}
	_ = time.Second

	_ = proto.String
)

type Service interface {
	SayHello(in *HelloRequest, out *HelloReply) error
}

// AcceptServiceClient accepts connections on the listener and serves requests
// for each incoming connection.  Accept blocks; the caller typically
// invokes it in a go statement.
func AcceptServiceClient(lis net.Listener, x Service) {
	srv := rpc.NewServer()
	if err := srv.RegisterName("Service", x); err != nil {
		log.Fatal(err)
	}

	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Fatalf("lis.Accept(): %v\n", err)
		}
		go srv.ServeConn(conn)
	}
}

// RegisterService publish the given Service implementation on the server.
func RegisterService(srv *rpc.Server, x Service) error {
	if err := srv.RegisterName("Service", x); err != nil {
		return err
	}
	return nil
}

// NewServiceServer returns a new Service Server.
func NewServiceServer(x Service) *rpc.Server {
	srv := rpc.NewServer()
	if err := srv.RegisterName("Service", x); err != nil {
		log.Fatal(err)
	}
	return srv
}

// ListenAndServeService listen announces on the local network address laddr
// and serves the given Service implementation.
func ListenAndServeService(network, addr string, x Service) error {
	lis, err := net.Listen(network, addr)
	if err != nil {
		return err
	}
	defer lis.Close()

	srv := rpc.NewServer()
	if err := srv.RegisterName("Service", x); err != nil {
		return err
	}

	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Fatalf("lis.Accept(): %v\n", err)
		}
		go srv.ServeConn(conn)
	}
}

// ServeService serves the given Service implementation.
func ServeService(conn io.ReadWriteCloser, x Service) {
	srv := rpc.NewServer()
	if err := srv.RegisterName("Service", x); err != nil {
		log.Fatal(err)
	}
	srv.ServeConn(conn)
}

type ServiceClient struct {
	*rpc.Client
}

// NewServiceClient returns a Service stub to handle
// requests to the set of Service at the other end of the connection.
func NewServiceClient(conn io.ReadWriteCloser) *ServiceClient {
	c := rpc.NewClient(conn)
	return &ServiceClient{c}
}

func (c *ServiceClient) SayHello(in *HelloRequest) (out *HelloReply, err error) {
	if in == nil {
		in = new(HelloRequest)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(HelloReply)
	if err = c.Call("Service.SayHello", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *ServiceClient) AsyncSayHello(in *HelloRequest, out *HelloReply, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(HelloRequest)
	}
	return c.Go(
		"Service.SayHello",
		in, out,
		done,
	)
}

// DialService connects to an Service at the specified network address.
func DialService(network, addr string) (*ServiceClient, error) {
	c, err := rpc.Dial(network, addr)
	if err != nil {
		return nil, err
	}
	return &ServiceClient{c}, nil
}

// DialServiceTimeout connects to an Service at the specified network address.
func DialServiceTimeout(network, addr string, timeout time.Duration) (*ServiceClient, error) {
	conn, err := net.DialTimeout(network, addr, timeout)
	if err != nil {
		return nil, err
	}
	return &ServiceClient{rpc.NewClient(conn)}, nil
}
