// Code generated by protoc-gen-go.
// source: wire.proto
// DO NOT EDIT!

/*
Package protorpc_wire is a generated protocol buffer package.


	protorpc wire format wrapper

	0. Frame Format
	len : uvarint64
	data: byte[len]

	1. Client Send Request
	Send RequestHeader: sendFrame(zsock, hdr, len(hdr))
	Send Request: sendFrame(zsock, body, hdr.snappy_compressed_request_len)

	2. Server Recv Request
	Recv RequestHeader: recvFrame(zsock, hdr, max_hdr_len, 0)
	Recv Request: recvFrame(zsock, body, hdr.snappy_compressed_request_len, 0)

	3. Server Send Response
	Send ResponseHeader: sendFrame(zsock, hdr, len(hdr))
	Send Response: sendFrame(zsock, body, hdr.snappy_compressed_response_len)

	4. Client Recv Response
	Recv ResponseHeader: recvFrame(zsock, hdr, max_hdr_len, 0)
	Recv Response: recvFrame(zsock, body, hdr.snappy_compressed_response_len, 0)


It is generated from these files:
	wire.proto

It has these top-level messages:
	RequestHeader
	ResponseHeader
*/
package protorpc_wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequestHeader struct {
	Id                         uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Method                     string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	RawRequestLen              uint32 `protobuf:"varint,3,opt,name=raw_request_len" json:"raw_request_len,omitempty"`
	SnappyCompressedRequestLen uint32 `protobuf:"varint,4,opt,name=snappy_compressed_request_len" json:"snappy_compressed_request_len,omitempty"`
	Checksum                   uint32 `protobuf:"varint,5,opt,name=checksum" json:"checksum,omitempty"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}

type ResponseHeader struct {
	Id                          uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Error                       string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	RawResponseLen              uint32 `protobuf:"varint,3,opt,name=raw_response_len" json:"raw_response_len,omitempty"`
	SnappyCompressedResponseLen uint32 `protobuf:"varint,4,opt,name=snappy_compressed_response_len" json:"snappy_compressed_response_len,omitempty"`
	Checksum                    uint32 `protobuf:"varint,5,opt,name=checksum" json:"checksum,omitempty"`
	ErrorCode                   int32  `protobuf:"varint,6,opt,name=error_code" json:"error_code,omitempty"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
